# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Check-PR-Win-Build

on:
  pull_request:
    types:
      - opened
    branches:
      - master
      - 'v*.*.*'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BIN_PATH: ./bin/x64

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  PRMergeBuild:
    name: Build
    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # setup nodejs
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        cache-dependency-path: ${{env.SOLUTION_FILE_PATH}}
    - name: Install dependencies
      run: npm clean-install
    - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
      run: npm audit signatures

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

