# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PR-Merge-Win-Build

on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - 'v*.*.*'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BIN_PATH: ./bin/x64

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  PRMergeBuild:
    if: github.event.pull_request.merged == true
    name: Build & Upload artifacts
    runs-on: windows-latest
    permissions: write-all

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # setup nodejs
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
        name: artifact # ${{ steps.tag_version.outputs.new_tag }}
        path: ${{env.BIN_PATH}}
